In [2]:
import requests
import pandas as pd

In [5]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=1")

In [21]:
df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]

In [23]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,31.4774,8.710,28269
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,76.1872,8.687,21424
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,14.3596,8.571,12945
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,20.8512,8.564,16419
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,28.6652,8.548,9115

In [30]:
import requests
import pandas as pd
import time

all_data = []

for i in range(1, 508):
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page={i}"
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()  # Raise exception for HTTP errors
        results = response.json().get('results', [])
        temp_df = pd.DataFrame(results)[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
        all_data.append(temp_df)
        print(f"Page {i} fetched successfully.")
        time.sleep(0.5)  # Avoid hitting API rate limits
    except requests.exceptions.Timeout:
        print(f"Timeout occurred on page {i}. Retrying...")
        time.sleep(5)
        continue
    except requests.exceptions.RequestException as e:
        print(f"Request failed on page {i}: {e}")
        continue

# Combine all the DataFrames
df = pd.concat(all_data, ignore_index=True)

Page 1 fetched successfully.
Page 2 fetched successfully.
Page 3 fetched successfully.
Page 4 fetched successfully.
Page 5 fetched successfully.
Page 6 fetched successfully.
Page 7 fetched successfully.
Page 8 fetched successfully.
Page 9 fetched successfully.
Page 10 fetched successfully.
Page 11 fetched successfully.
Page 12 fetched successfully.
Page 13 fetched successfully.
Page 14 fetched successfully.
Page 15 fetched successfully.
Page 16 fetched successfully.
Page 17 fetched successfully.
Page 18 fetched successfully.
Page 19 fetched successfully.
Page 20 fetched successfully.
Page 21 fetched successfully.
Page 22 fetched successfully.
Page 23 fetched successfully.
Page 24 fetched successfully.
Page 25 fetched successfully.
Page 26 fetched successfully.
Page 27 fetched successfully.
Page 28 fetched successfully.
Page 29 fetched successfully.
Page 30 fetched successfully.
Page 31 fetched successfully.
Page 32 fetched successfully.
Page 33 fetched successfully.
Page 34 fetched successfully.
Page 35 fetched successfully.
Page 36 fetched successfully.
Page 37 fetched successfully.
Page 38 fetched successfully.
Page 39 fetched successfully.
Page 40 fetched successfully.
Page 41 fetched successfully.
Page 42 fetched successfully.
Page 43 fetched successfully.
Page 44 fetched successfully.
Page 45 fetched successfully.
Page 46 fetched successfully.
Page 47 fetched successfully.
Page 48 fetched successfully.
Page 49 fetched successfully.
Page 50 fetched successfully.
Page 51 fetched successfully.
Page 52 fetched successfully.
Page 53 fetched successfully.
Page 54 fetched successfully.
Page 55 fetched successfully.
Page 56 fetched successfully.
Page 57 fetched successfully.
Page 58 fetched successfully.
Page 59 fetched successfully.
Page 60 fetched successfully.
Page 61 fetched successfully.
Page 62 fetched successfully.
Page 63 fetched successfully.
Page 64 fetched successfully.
Page 65 fetched successfully.
Page 66 fetched successfully.
Page 67 fetched successfully.
Page 68 fetched successfully.
Page 69 fetched successfully.
Page 70 fetched successfully.
Page 71 fetched successfully.
Page 72 fetched successfully.
Page 73 fetched successfully.
Page 74 fetched successfully.
Page 75 fetched successfully.
Page 76 fetched successfully.
Page 77 fetched successfully.
Page 78 fetched successfully.
Page 79 fetched successfully.
Page 80 fetched successfully.
Page 81 fetched successfully.
Page 82 fetched successfully.
Page 83 fetched successfully.
Page 84 fetched successfully.
Page 85 fetched successfully.
Page 86 fetched successfully.
Page 87 fetched successfully.
Page 88 fetched successfully.
Page 89 fetched successfully.
Page 90 fetched successfully.
Page 91 fetched successfully.
Page 92 fetched successfully.
Page 93 fetched successfully.
Page 94 fetched successfully.
Page 95 fetched successfully.
Page 96 fetched successfully.
Page 97 fetched successfully.
Page 98 fetched successfully.
Page 99 fetched successfully.
Page 100 fetched successfully.
Page 101 fetched successfully.
Page 102 fetched successfully.
Page 103 fetched successfully.
Page 104 fetched successfully.
Page 105 fetched successfully.
Page 106 fetched successfully.
Page 107 fetched successfully.
Page 108 fetched successfully.
Page 109 fetched successfully.
Page 110 fetched successfully.
Page 111 fetched successfully.
Page 112 fetched successfully.
Page 113 fetched successfully.
Page 114 fetched successfully.
Page 115 fetched successfully.
Page 116 fetched successfully.
Page 117 fetched successfully.
Page 118 fetched successfully.
Page 119 fetched successfully.
Page 120 fetched successfully.
Page 121 fetched successfully.
Page 122 fetched successfully.
Page 123 fetched successfully.
Page 124 fetched successfully.
Page 125 fetched successfully.
Page 126 fetched successfully.
Page 127 fetched successfully.
Page 128 fetched successfully.
Page 129 fetched successfully.
Page 130 fetched successfully.
Page 131 fetched successfully.
Page 132 fetched successfully.
Page 133 fetched successfully.
Page 134 fetched successfully.
Page 135 fetched successfully.
Page 136 fetched successfully.
Page 137 fetched successfully.
Page 138 fetched successfully.
Page 139 fetched successfully.
Page 140 fetched successfully.
Page 141 fetched successfully.
Page 142 fetched successfully.
Page 143 fetched successfully.
Page 144 fetched successfully.
Page 145 fetched successfully.
Page 146 fetched successfully.
Page 147 fetched successfully.
Page 148 fetched successfully.
Page 149 fetched successfully.
Page 150 fetched successfully.
Page 151 fetched successfully.
Page 152 fetched successfully.
Page 153 fetched successfully.
Page 154 fetched successfully.
Page 155 fetched successfully.
Page 156 fetched successfully.
Page 157 fetched successfully.
Page 158 fetched successfully.
Page 159 fetched successfully.
Page 160 fetched successfully.
Page 161 fetched successfully.
Page 162 fetched successfully.
Page 163 fetched successfully.
Page 164 fetched successfully.
Page 165 fetched successfully.
Page 166 fetched successfully.
Page 167 fetched successfully.
Page 168 fetched successfully.
Page 169 fetched successfully.
Page 170 fetched successfully.
Page 171 fetched successfully.
Page 172 fetched successfully.
Page 173 fetched successfully.
Page 174 fetched successfully.
Page 175 fetched successfully.
Page 176 fetched successfully.
Page 177 fetched successfully.
Page 178 fetched successfully.
Page 179 fetched successfully.
Page 180 fetched successfully.
Page 181 fetched successfully.
Page 182 fetched successfully.
Page 183 fetched successfully.
Page 184 fetched successfully.
Page 185 fetched successfully.
Page 186 fetched successfully.
Page 187 fetched successfully.
Page 188 fetched successfully.
Page 189 fetched successfully.
Page 190 fetched successfully.
Page 191 fetched successfully.
Page 192 fetched successfully.
Page 193 fetched successfully.
Page 194 fetched successfully.
Page 195 fetched successfully.
Page 196 fetched successfully.
Page 197 fetched successfully.
Page 198 fetched successfully.
Page 199 fetched successfully.
Page 200 fetched successfully.
Page 201 fetched successfully.
Page 202 fetched successfully.
Page 203 fetched successfully.
Page 204 fetched successfully.
Page 205 fetched successfully.
Page 206 fetched successfully.
Page 207 fetched successfully.
Page 208 fetched successfully.
Page 209 fetched successfully.
Page 210 fetched successfully.
Page 211 fetched successfully.
Page 212 fetched successfully.
Page 213 fetched successfully.
Page 214 fetched successfully.
Page 215 fetched successfully.
Page 216 fetched successfully.
Page 217 fetched successfully.
Page 218 fetched successfully.
Page 219 fetched successfully.
Page 220 fetched successfully.
Page 221 fetched successfully.
Page 222 fetched successfully.
Page 223 fetched successfully.
Page 224 fetched successfully.
Page 225 fetched successfully.
Page 226 fetched successfully.
Page 227 fetched successfully.
Page 228 fetched successfully.
Page 229 fetched successfully.
Page 230 fetched successfully.
Page 231 fetched successfully.
Page 232 fetched successfully.
Page 233 fetched successfully.
Page 234 fetched successfully.
Page 235 fetched successfully.
Page 236 fetched successfully.
Page 237 fetched successfully.
Page 238 fetched successfully.
Page 239 fetched successfully.
Page 240 fetched successfully.
Page 241 fetched successfully.
Page 242 fetched successfully.
Page 243 fetched successfully.
Page 244 fetched successfully.
Page 245 fetched successfully.
Page 246 fetched successfully.
Page 247 fetched successfully.
Page 248 fetched successfully.
Page 249 fetched successfully.
Page 250 fetched successfully.
Page 251 fetched successfully.
Page 252 fetched successfully.
Page 253 fetched successfully.
Page 254 fetched successfully.
Page 255 fetched successfully.
Page 256 fetched successfully.
Page 257 fetched successfully.
Page 258 fetched successfully.
Page 259 fetched successfully.
Page 260 fetched successfully.
Page 261 fetched successfully.
Page 262 fetched successfully.
Page 263 fetched successfully.
Page 264 fetched successfully.
Page 265 fetched successfully.
Page 266 fetched successfully.
Page 267 fetched successfully.
Page 268 fetched successfully.
Page 269 fetched successfully.
Page 270 fetched successfully.
Page 271 fetched successfully.
Page 272 fetched successfully.
Page 273 fetched successfully.
Page 274 fetched successfully.
Page 275 fetched successfully.
Page 276 fetched successfully.
Page 277 fetched successfully.
Page 278 fetched successfully.
Page 279 fetched successfully.
Page 280 fetched successfully.
Page 281 fetched successfully.
Page 282 fetched successfully.
Page 283 fetched successfully.
Page 284 fetched successfully.
Page 285 fetched successfully.
Page 286 fetched successfully.
Page 287 fetched successfully.
Page 288 fetched successfully.
Page 289 fetched successfully.
Page 290 fetched successfully.
Page 291 fetched successfully.
Page 292 fetched successfully.
Page 293 fetched successfully.
Page 294 fetched successfully.
Page 295 fetched successfully.
Page 296 fetched successfully.
Page 297 fetched successfully.
Page 298 fetched successfully.
Page 299 fetched successfully.
Page 300 fetched successfully.
Page 301 fetched successfully.
Page 302 fetched successfully.
Page 303 fetched successfully.
Page 304 fetched successfully.
Page 305 fetched successfully.
Page 306 fetched successfully.
Page 307 fetched successfully.
Page 308 fetched successfully.
Page 309 fetched successfully.
Page 310 fetched successfully.
Page 311 fetched successfully.
Page 312 fetched successfully.
Page 313 fetched successfully.
Page 314 fetched successfully.
Page 315 fetched successfully.
Page 316 fetched successfully.
Page 317 fetched successfully.
Page 318 fetched successfully.
Page 319 fetched successfully.
Page 320 fetched successfully.
Page 321 fetched successfully.
Page 322 fetched successfully.
Page 323 fetched successfully.
Page 324 fetched successfully.
Page 325 fetched successfully.
Page 326 fetched successfully.
Page 327 fetched successfully.
Page 328 fetched successfully.
Page 329 fetched successfully.
Page 330 fetched successfully.
Page 331 fetched successfully.
Page 332 fetched successfully.
Page 333 fetched successfully.
Page 334 fetched successfully.
Page 335 fetched successfully.
Page 336 fetched successfully.
Page 337 fetched successfully.
Page 338 fetched successfully.
Page 339 fetched successfully.
Page 340 fetched successfully.
Page 341 fetched successfully.
Page 342 fetched successfully.
Page 343 fetched successfully.
Page 344 fetched successfully.
Page 345 fetched successfully.
Page 346 fetched successfully.
Page 347 fetched successfully.
Page 348 fetched successfully.
Page 349 fetched successfully.
Page 350 fetched successfully.
Page 351 fetched successfully.
Page 352 fetched successfully.
Page 353 fetched successfully.
Page 354 fetched successfully.
Page 355 fetched successfully.
Page 356 fetched successfully.
Page 357 fetched successfully.
Page 358 fetched successfully.
Page 359 fetched successfully.
Page 360 fetched successfully.
Page 361 fetched successfully.
Page 362 fetched successfully.
Page 363 fetched successfully.
Page 364 fetched successfully.
Page 365 fetched successfully.
Page 366 fetched successfully.
Page 367 fetched successfully.
Page 368 fetched successfully.
Page 369 fetched successfully.
Page 370 fetched successfully.
Page 371 fetched successfully.
Page 372 fetched successfully.
Page 373 fetched successfully.
Page 374 fetched successfully.
Page 375 fetched successfully.
Page 376 fetched successfully.
Page 377 fetched successfully.
Page 378 fetched successfully.
Page 379 fetched successfully.
Page 380 fetched successfully.
Page 381 fetched successfully.
Page 382 fetched successfully.
Page 383 fetched successfully.
Page 384 fetched successfully.
Page 385 fetched successfully.
Page 386 fetched successfully.
Page 387 fetched successfully.
Page 388 fetched successfully.
Page 389 fetched successfully.
Page 390 fetched successfully.
Page 391 fetched successfully.
Page 392 fetched successfully.
Page 393 fetched successfully.
Page 394 fetched successfully.
Page 395 fetched successfully.
Page 396 fetched successfully.
Page 397 fetched successfully.
Page 398 fetched successfully.
Page 399 fetched successfully.
Page 400 fetched successfully.
Page 401 fetched successfully.
Page 402 fetched successfully.
Page 403 fetched successfully.
Page 404 fetched successfully.
Page 405 fetched successfully.
Page 406 fetched successfully.
Page 407 fetched successfully.
Page 408 fetched successfully.
Page 409 fetched successfully.
Page 410 fetched successfully.
Page 411 fetched successfully.
Page 412 fetched successfully.
Page 413 fetched successfully.
Page 414 fetched successfully.
Page 415 fetched successfully.
Page 416 fetched successfully.
Page 417 fetched successfully.
Page 418 fetched successfully.
Page 419 fetched successfully.
Page 420 fetched successfully.
Page 421 fetched successfully.
Page 422 fetched successfully.
Page 423 fetched successfully.
Page 424 fetched successfully.
Page 425 fetched successfully.
Page 426 fetched successfully.
Page 427 fetched successfully.
Page 428 fetched successfully.
Page 429 fetched successfully.
Page 430 fetched successfully.
Page 431 fetched successfully.
Page 432 fetched successfully.
Timeout occurred on page 433. Retrying...
Page 434 fetched successfully.
Page 435 fetched successfully.
Page 436 fetched successfully.
Page 437 fetched successfully.
Page 438 fetched successfully.
Page 439 fetched successfully.
Page 440 fetched successfully.
Page 441 fetched successfully.
Page 442 fetched successfully.
Page 443 fetched successfully.
Page 444 fetched successfully.
Page 445 fetched successfully.
Page 446 fetched successfully.
Page 447 fetched successfully.
Page 448 fetched successfully.
Page 449 fetched successfully.
Page 450 fetched successfully.
Page 451 fetched successfully.
Page 452 fetched successfully.
Page 453 fetched successfully.
Page 454 fetched successfully.
Page 455 fetched successfully.
Page 456 fetched successfully.
Page 457 fetched successfully.
Page 458 fetched successfully.
Page 459 fetched successfully.
Page 460 fetched successfully.
Page 461 fetched successfully.
Page 462 fetched successfully.
Page 463 fetched successfully.
Page 464 fetched successfully.
Page 465 fetched successfully.
Page 466 fetched successfully.
Page 467 fetched successfully.
Page 468 fetched successfully.
Page 469 fetched successfully.
Page 470 fetched successfully.
Page 471 fetched successfully.
Page 472 fetched successfully.
Page 473 fetched successfully.
Page 474 fetched successfully.
Page 475 fetched successfully.
Page 476 fetched successfully.
Page 477 fetched successfully.
Page 478 fetched successfully.
Page 479 fetched successfully.
Page 480 fetched successfully.
Page 481 fetched successfully.
Page 482 fetched successfully.
Page 483 fetched successfully.
Page 484 fetched successfully.
Page 485 fetched successfully.
Page 486 fetched successfully.
Page 487 fetched successfully.
Page 488 fetched successfully.
Page 489 fetched successfully.
Page 490 fetched successfully.
Page 491 fetched successfully.
Page 492 fetched successfully.
Page 493 fetched successfully.
Page 494 fetched successfully.
Page 495 fetched successfully.
Page 496 fetched successfully.
Page 497 fetched successfully.
Page 498 fetched successfully.
Page 499 fetched successfully.
Page 500 fetched successfully.
Request failed on page 501: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=501
Request failed on page 502: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=502
Request failed on page 503: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=503
Request failed on page 504: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=504
Request failed on page 505: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=505
Request failed on page 506: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=506
Request failed on page 507: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?api_key=fbf85508700a25045bc8add07e80d431&language=en-US&page=507

In [31]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,31.4774,8.710,28269
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,76.1872,8.687,21424
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,14.3596,8.571,12945
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,20.8512,8.564,16419
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,28.6652,8.548,9115
...,...,...,...,...,...,...,...
9975,853588,Prey,A hiking trip into the wild turns into a despe...,2021-09-10,1.2359,4.679,361
9976,14863,Anaconda 3: Offspring,A mercenary-for-hire accepts a mission from a ...,2008-10-23,3.4163,4.700,329
9977,529983,The Poison Rose,A down-on-his-luck PI is hired by his old flam...,2019-05-23,2.0425,4.672,355
9978,76487,The Devil Inside,"In Italy, a woman becomes involved in a series...",2012-01-06,1.7658,4.668,800
9979,871964,Nobody Sleeps in the Woods Tonight 2,When something horrible happens to the only su...,2021-10-27,2.0023,4.664,311

In [33]:
df.shape

(9980, 7)

In [34]:
df.to_csv('Popular_movies.csv')